name: Github Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  depoly:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{github.workflow}}-${{github.ref}}
    steps:
      - uses: actions/checkout@2

      - name: Setup Node
        uses: actions/setup-node@2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@2
        with:
          path: ~/.npm
          key: ${{runner.on}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node-

      - run: npm ci
      # - run: npm run format
      # - run: npm run test
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{github.ref == 'refs/heads/main'}}
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./publish
